In [1]:
# Put in PaGraph/partition/
# Remove data import in both dg.py and ordering.py
# 
import ordering
from dg import dg
from ogb.nodeproppred import DglNodePropPredDataset
import numpy as np
import os

In [2]:
ROOT_DIR = '/data/sandeep'
PAGRAPH_DIR = '/data/sandeep/pagraph/'
FILENAME = 'obgn_arxiv'
dataset = DglNodePropPredDataset('ogbn-arxiv',root=ROOT_DIR)
graph = dataset[0][0]
graph = graph.add_self_loop()
split_idx = dataset.get_idx_split()

In [3]:
scipyCOO = graph.adj(scipy_fmt='coo')
scipyCSR = scipyCOO.tocsc()

In [4]:
adj, vmap = ordering.reordering(scipyCSR, depth=3)

=>99%


In [5]:
train_nids = split_idx['train']
train_nids = np.sort(vmap[train_nids])

In [6]:
p_v, p_trainv = dg(4, adj, train_nids, 3)

total vertices: 169343 | train vertices: 90941
=>99%
vertex# with self-reliance:  126904
vertex# w/o  self-reliance:  22702
vertex# with self-reliance:  126070
vertex# w/o  self-reliance:  22734
vertex# with self-reliance:  124972
vertex# w/o  self-reliance:  22776
vertex# with self-reliance:  126197
vertex# w/o  self-reliance:  22729


In [8]:
np.save(PAGRAPH_DIR+FILENAME + '_p_v', p_v)
np.save(PAGRAPH_DIR+FILENAME + '_p_trainv', p_trainv)

/home/jfalus/OCC-GNN/venv/lib/python3.8/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [10]:
x=np.load(PAGRAPH_DIR+FILENAME + '_p_v'+'.npy', allow_pickle=True)
y=np.load(PAGRAPH_DIR+FILENAME + '_p_trainv'+'.npy', allow_pickle=True)

[array([     0,      1,      2, ..., 169339, 169340, 169342])
 array([     1,      2,      3, ..., 169340, 169341, 169342])
 array([     1,      2,      3, ..., 169338, 169341, 169342])
 array([     0,      1,      2, ..., 169338, 169339, 169340])]
[array([     3,      4,      6, ..., 169255, 169312, 169316])
 array([     2,      5,      8, ..., 169309, 169314, 169318])
 array([     1,      7,      9, ..., 169311, 169315, 169321])
 array([     0,     10,     18, ..., 169307, 169313, 169317])]
